#!/usr/bin/env bash

found_error=false

# lint the actual library
echo 'Linting the library'
$(npm bin)/eslint -c index.js index.js
echo -e 'Passed\n'

# lint the pass cases
pass_cases=$(find `pwd`/test/fixtures/passes -name "*.js")

for fname in $pass_cases; do
  echo "Checking that eslint config passes for ${fname#`pwd`/}..."
  $(npm bin)/eslint -c index.js $fname
  
  if [ $? != "0" ]; then
    found_error=true
    echo -e "!!! ERROR FOUND FOR LAST FILE.\n    See message above.\n\n"
  fi
done


# lint the fail cases and assert they fail
fail_cases=$(find `pwd`/test/fixtures/fails -name "*.js")

for fname in $fail_cases; do
  echo "Checking that eslint config fails for ${fname#`pwd`/}..."
  $(npm bin)/eslint -c index.js $fname > /dev/null
  
  if [ $? != "1" ]; then
    found_error=true
    echo -e "!!! ERROR FOR LAST FILE, IT DID *NOT* FAIL LINTING LIKE IT SHOULD.\n    See message above.\n\n"
  fi
done

if [ "$found_error" = true ]; then
  exit 1
fi
